pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.config'
# This is for the testing PR approvers still its not working.
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
  enabled: false
  
- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  enabled: false