pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
pr: 
  branches: 
    include: 
    - master
    - develop
    - feature/test
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.config'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'